tip on viewing node async output, see issue #1468
BetterThanTomorrow/calva pull request #1493
Opened 2022-01-22 16:34 UTC by agoldhammer

## What has Changed?

- Describes workaround for issue discussed in #1468.
- @pez suggests creating a Tips and Tricks section under Etcetera where this might fit.
-

Fixes #1468

## My Calva PR Checklist

I have:

- [x ] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x ] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [ ] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x ] - directed at "published" because this is a doc fix only
- [ ] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x ] Added to or updated docs in this branch, if appropriate

- [x ] Created the issue I am fixing/addressing, if it was not present.

Ping @pez, @bpringe

2022-01-23 20:03 UTC, bpringe requested changes
Thanks for adding this. Just a small change requested (typo).

2022-01-23 20:03 UTC, bpringe commented on docs/site/async-out.md
> +3. Issue the command **Calva: Connect to a running REPL server in your project**, `ctrl+alt+c ctrl+alt+c`. For project type select `shadow-cljs`, accepted the proposed `localhost:<some-port>`, and fo
```suggestion
3. Issue the command **Calva: Connect to a running REPL server in your project**, `ctrl+alt+c ctrl+alt+c`. For project type select `shadow-cljs`, accepted the proposed `localhost:<some-port>`, and for `build` select `node-repl`.
```

2022-01-23 20:07 UTC, bpringe commented
You can add this under Etcetera in the menu by using the `mkdocs.yml` file.

2022-01-23 20:22 UTC, agoldhammer commented
> You can add this under Etcetera in the menu by using the `mkdocs.yml` file.

Thanks. Awaiting @pez instructions on what branch to target.

2022-01-24 08:10 UTC, PEZ commented
@agoldhammer , directing it at `published` is fine.

2022-01-24 15:29 UTC, PEZ commented
Thanks! Have you tested to build the docs site locally?

2022-01-24 15:31 UTC, agoldhammer commented
Yes, works for me.

On Mon, Jan 24, 2022 at 10:30 AM Peter Strömberg ***@***.***>
wrote:

> Thanks! Have you tested to build the docs site locally?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetterThanTomorrow/calva/pull/1493#issuecomment-1020223072>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJZLF3TBSSMJEO5Y355PSDUXVWAHANCNFSM5MSFKFGQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-24 16:11 UTC, merged

2022-01-24 16:11 UTC, PEZ commented
🎉 Thanks! 🙏 ❤️