initial integration tests
BetterThanTomorrow/calva pull request #1518
Opened 2022-02-06 13:37 UTC by Cyrik

## What has Changed?

- added integration for nrepl start

Fixes #

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [ ] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [ ] Added to or updated docs in this branch, if appropriate
- [ ] Tests
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
     - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [ ] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [ ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [ ] Created the issue I am fixing/addressing, if it was not present.

Ping @pez, @bpringe

2022-02-06 13:38 UTC, Cyrik commented
still very much playing around, but wanted to share my initial working version

2022-02-16 15:00 UTC, PEZ commented on .vscode/launch.json
> +            "IS_DEBUG": "true",
This looks a bit odd?

2022-02-16 15:10 UTC, PEZ requested changes
This is wonderful!!

The name of the test is the only thing I'd like fixed before merging.

2022-02-16 15:10 UTC, PEZ commented on src/extension-test/integration/suite/extension-test.ts
> +        console.log('connect to repl');
This probably should be _'start repl and connect (jack-in)'_ as _connect_ has a the special meaning in Calva of assuming the REPL is already started.

2022-02-16 15:28 UTC, Cyrik commented on .vscode/launch.json
> +            "IS_DEBUG": "true",
ah whoops, that was an accident, good catch.

2022-02-16 15:56 UTC, PEZ commented on .vscode/launch.json
> +            "IS_DEBUG": "true",
Isn't it strange that it passed the prettier test step, @corasaurus-hex ?

2022-02-16 15:57 UTC, PEZ approved these changes
🙏 ❤️ 🎉

2022-02-16 15:57 UTC, merged

2022-02-16 16:14 UTC, corasaurus-hex commented on .vscode/launch.json
> +            "IS_DEBUG": "true",
Prettier just formats typescript and javascript right now. https://github.com/BetterThanTomorrow/calva/blob/published/package.json#L2584-L2585

We could expand it to also format json and other file types, though!