Feature/notebook
BetterThanTomorrow/calva pull request #1820
Opened 2022-08-06 21:50 UTC by Cyrik

## What has changed?

- adds a notebook provider
- adds a Notebook Kernel
You can try it out by right clicking on any clojure file -> `Open with...` -> `Calva Notebook`.

Currently saving isn't implemented yet.

Fixes #

## My Calva PR Checklist

If this PR involves only documentation changes, I have:

- [ ] Read [Editing Documentation](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva#editing-documentation)
- [ ] Directed this pull request at the `published` branch.
- [ ] Built the site locally (if the changes were more involved than simple typo fixes), and verified that the site is presented as expected.
- [ ] Referenced the issue I am fixing/addressing _in a commit message for the pull request_ (if there was is an issue for the documentation change)
  - [ ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
  - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.

If this PR involves code changes, I have:

- [ ] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [ ] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [ ] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [ ] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [ ] Added to or updated docs in this branch, if appropriate
- [ ] Tests
  - [ ] Tested the particular change
  - [ ] Figured if the change might have some side effects and tested those as well.
  - [ ] Smoke tested the extension as such.
  - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [ ] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
  - [ ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
  - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [ ] Created the issue I am fixing/addressing, if it was not present.
- [ ] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [ ] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

2022-08-07 00:41 UTC, Cyrik commented
So this is working "fully".
There's only one thing I'd like to fix before releasing this as MVP: saving currently reformats your file a little since I don't keep track of the whitespace between code blocks. @PEZ I'm using the LispCursor to get the top-level forms, is there something better that would also give me the whitespace ranges? Otherwise, I'll build it myself.
Other than that I'm being very unsafe with error handling and pretty printing, but I think that's ok for now, especially since this is a different view on the file that you can ignore if it's not working for your particular output size.

2022-08-09 08:32 UTC, PEZ commented
Thanks for this work, @Cyrik! ❤️ 

I'm unfamiliar with notebooks. Can you explain a bit about what the provider and kernel responsibilities are?

> I'm using the LispCursor to get the top-level forms, is there something better that would also give me the whitespace ranges? Otherwise, I'll build it myself.

Not really. There are some facilities for collecting whitespace information around the cursor, but I don't know how much use you could have for those. If _whitespace_ here means _everything else, but top level forms_, i.e. including comments, then the whitespace ranges are something like the inverse of the top level ranges, I think. Otherwise... if comments should be editable, maybe we should have a version of the top-level-ranges that includes ranges for the comment blocks?

I'd like to merge this, as is, and then we can build on it. However, would be good with a docs page for Notebooks so that users can orient themselves a bit on what to expect.

2022-08-09 09:16 UTC, Cyrik commented
Sure, but I'll have to keep it brief since I have to run for now.
The notebookProvider is a class that's gets called by vscode when you open or save a notebook. The deserialize method gets the content of the opened file and is supposed to return notebook cells that represent the file. The serialize method gets called on save and gets the cells and need to transform them into a string that is going to be written to the file.
You can go more complicated here and load arbitrary stuff from other sources or do transformations, but my basic implementation just wants to make every top level sexp into its own code block. To perserve comments and whitespace I'll have to go a little extra so that I can write them back out on save.

The inverse sounds like an OK way to go for now, I'll try to add that this to the PR. I'll also add a little bit to the docs. As you said, we can make this better in follow-up PRs and this feature is opt-in anyway.

2022-08-09 21:11 UTC, Cyrik commented
Fixed saving of whitespace/comments.
Handling of this could be a lot better, but it will save out the same input, so I'm happy for an alpha.

Also added a doc, although I'm not sure what to put into it 😅 

Happy for any suggestions for v0, otherwise I'd add a changelog entry and call this done, and work on improvements in the next version.

2022-08-10 01:25 UTC, bpringe commented on package-lock.json
> +      "deprecated": "this version had an improper engines field added, update to 1.1.1",
yikes... I'll make a task for this

2022-08-10 01:26 UTC, bpringe commented on package-lock.json
> +      "deprecated": "this version had an improper engines field added, update to 1.1.1",
And the other "deprecated" dep issues in this file

2022-08-10 01:27 UTC, bpringe commented on package-lock.json
> +      "deprecated": "this version had an improper engines field added, update to 1.1.1",
https://github.com/BetterThanTomorrow/calva/issues/1822

2022-08-10 01:34 UTC, bpringe commented on test-data/notebook.clj
> +"<html> <body>testing<h2>HTML Image</h2><img src='https://raw.githubusercontent.com/BetterThanTomorrow/calva/dev/assets/calva-64h.png'></body></html>"
Prime opportunity for a Rickroll.

2022-08-10 01:35 UTC, bpringe approved these changes

2022-08-10 01:36 UTC, bpringe requested changes
Just need a changelog entry and I think we're good to merge. 🎉 Thanks again for this!

2022-08-10 08:03 UTC, PEZ commented
Been playing a bit with this now and I must say it's lovely. ❤️ This could very well get me started as a notebooks user.

I've updated the documentation page a bit and added it to the **Features** section.

**NB**: There is a quite nasty bug with comments preceding the first form not being retained. 

Some suggestions:

* I think the name **Clojure Notebook** is better than **Calva Notebook**. I used this name in the docs update, but haven't changed it in the config/code.
* I'd like an issue created about adding basic Notebook support. It could include a bit about what notebooks are and why it would be good to have them. This issue is what should be referred in the change log.
* Related to the issue ticket, I think we should start a Discussions thread about Notebooks. It seems to be a very large subject with lots of choices and priorities and trade-offs.

2022-08-10 11:49 UTC, Cyrik commented on test-data/notebook.clj
> +"<html> <body>testing<h2>HTML Image</h2><img src='https://raw.githubusercontent.com/BetterThanTomorrow/calva/dev/assets/calva-64h.png'></body></html>"
done

2022-08-10 12:39 UTC, PEZ reviewed
See my comments above. =)

2022-08-10 13:06 UTC, Cyrik commented
I've renamed the description to "Clojure Notebook" but set the id to "calva-clojure-notebook" to prevent clashes with a potential extension that also provides Clojure notebooks.
Issue and discussion are also created and the "comment or whitespace before the first exp" is also fixed.
I think this can be merged @PEZ

2022-08-13 19:42 UTC, bpringe commented on docs/site/notebooks.md
> +You can open any clojure file as a notebook by right clicking the file -> `Open with...` -> `Calva Notebook`.
```suggestion
You can open any clojure file as a notebook by right clicking the file -> `Open with...` -> `Clojure Notebook`.
```

2022-08-13 19:43 UTC, bpringe commented on docs/site/notebooks.md
> +You can open any clojure file as a notebook by right clicking the file -> `Open with...` -> `Calva Notebook`.
I think this should be updated, right?

2022-08-13 19:44 UTC, bpringe approved these changes
Approving, but I made a doc update suggestion.

2022-08-13 21:13 UTC, merged